### ISSUE TITLE
Changes to files not having an affect (not being `watched`?)

### ISSUE THREAD

**Issue by yarnball** [gp3gp3gp3/react-jwt-auth#21]
Hi,

Thanks for this- it seems like the perfect repo for storing JWT tokens from my server.

However, I've made changes to the files (such as the URL in `/src/actions/index.js`) but it doesn't seem to have an affect.

Maybe it's getting its' value from the bundle.js?

I've tried installing `hot-loading` without success.

Can you advise?

Also, what is the command to build this project (for production)?

**Comment by yarnball** [comment]
I think it is related to webpack/package.json

Line 21 I just added `-hot` for a previous commit, and had some luck. However the latest commit does not watch for changes.

`"watch": "webpack --watch  --config ./webpack.dev.config.js -hot"`

**Comment by ultrox** [comment]
Your problem is solved!
https://github.com/ultrox/react-jwt-auth

For some reason hot reloading dose not work, so for now you need to hard reload to see the changes, but I guess you need to fix that.

**Comment by yarnball** [comment]
Thanks!

Requires page refresh, an improvement :)

Running `npm run build` doesn't seem to create a build or dist folder. Could you check that?

This is the result I get with `npm run build`

```
MacBook-Pro-7:1 mac1$ npm run build

> react-jwt-auth@1.0.0 build /Users/mac1/Dev/A51/FrontendReact/1
> npm run clean && npm run build:webpack


> react-jwt-auth@1.0.0 clean /Users/mac1/Dev/A51/FrontendReact/1
> rimraf dist


> react-jwt-auth@1.0.0 build:webpack /Users/mac1/Dev/A51/FrontendReact/1
> NODE_ENV=production webpack --config webpack.prod.config.js

Hash: 3a39261ecbe19961893e
Version: webpack 1.13.3
Time: 21750ms
        Asset     Size  Chunks             Chunk Names
    bundle.js   370 kB       0  [emitted]  main
bundle.js.map  3.27 MB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 473 hidden modules
```

**Comment by gp3gp3gp3** [comment]
Hey all!

@yarnball It's true I didn't set up the repo to include webpack hot loading, I'm glad to see you figured out how to set it up.
Running build just compiles the bundle.js and the map for it.  The site loads off that so it's completely static.

**Comment by gp3gp3gp3** [comment]
@yarnball @ultrox Feel free to make a pull request and I'll gladly merge it!  I really just made this repository to mess around with stuff, didn't really figure anybody else would come poking around here!  👍

**Comment by yarnball** [comment]
@gp3gp3gp3 

Thanks! Can you elaborate a little about getting the build to run a workable version? I copied the bundle.js and map to my server, but it would no load. I created an `index.html` file and still no luck.

This is a really nice example of handling JWT and I would like to run it on my server- so help is much appreciated!
